version: "3.1"

networks:
  valorant-net:
    driver: bridge

services:

  minio:
    image: minio/minio:RELEASE.2024-06-13T22-53-53Z
    container_name: minio
    hostname: minio
    restart: always
    volumes:
      - ./include/data/minio:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - valorant-net

  postgres:
    volumes:
      - ./backups:/backups
    networks:
      - valorant-net

  metabase:
    image: metabase/metabase:v0.50.4
    restart: always
    ports:
      - 3000:3000
    networks:
      - valorant-net
    volumes:
      - ./backups/databases/metabase.db:/metabase.db

  webserver:
    user: root
    networks:
      - valorant-net
    volumes:
      - ./backups:/usr/local/airflow/backups
      - ./tmp:/usr/local/airflow/tmp
      - /var/run/docker.sock:/var/run/docker.sock

  scheduler:
    user: root
    networks:
      - valorant-net
    volumes:
      - ./backups:/usr/local/airflow/backups
      - ./tmp:/usr/local/airflow/tmp
      - /var/run/docker.sock:/var/run/docker.sock:rw

  triggerer:
    networks:
      - valorant-net
    volumes:
      - ./backups:/usr/local/airflow/backups
      - ./tmp:/usr/local/airflow/tmp
      - /var/run/docker.sock:/var/run/docker.sock